services:
  - type: web
    name: between-the-lines
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && pip install gunicorn
    startCommand: python -m gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PYTHON_VERSION
        value: 3.10
