# Generated by Django 5.2.1 on 2025-05-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTL', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='description',
        ),
        migrations.AddField(
            model_name='doctor',
            name='introduction_video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='question_videos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='topic',
            field=models.CharField(choices=[('adhd', 'ADHD'), ('social_anxiety', 'Social Anxiety'), ('autism', 'Autism')], default='adhd', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('pedopsychiatre', 'Child Psychiatrist'), ('psy', 'Psychologist'), ('coach', 'Life Coach')], default='psy', max_length=20),
        ),
    ]
