# Generated by Django 5.2.1 on 2025-05-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTL', '0002_remove_doctor_description_doctor_introduction_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videos/questions/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='introduction_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/intro/'),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='question_videos',
        ),
        migrations.AddField(
            model_name='doctor',
            name='question_videos',
            field=models.ManyToManyField(blank=True, to='BTL.doctorvideo'),
        ),
    ]
