# Generated by Django 5.2.1 on 2025-05-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTL', '0004_doctorvideo_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='introduction_video',
        ),
        migrations.RemoveField(
            model_name='doctorvideo',
            name='file',
        ),
        migrations.AddField(
            model_name='doctor',
            name='introduction_video_url',
            field=models.URLField(blank=True, help_text='Google Drive video URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='doctorvideo',
            name='file_url',
            field=models.URLField(default=1, help_text='Google Drive video URL', max_length=500),
            preserve_default=False,
        ),
    ]
