# Generated by Django 5.2.1 on 2025-05-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTL', '0005_remove_doctor_introduction_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
